name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install system dependencies for Playwright
        run: sudo npx playwright install-deps

      - name: Install dependencies
        run: npm install

      - name: Clear Playwright cache
        run: npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test locator.spec.js
